### ISSUE TITLE
Python2 vs Python3

### ISSUE THREAD

**Issue by woywoy123** [ConsensusGroup/Haystack#18]
An issue has been reported where running the code with python3 will result in an error similar to; 

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from HayStack_API import HayStack, Run_HayStack_Client
  File "/home/XXX/github/Haystack/Test_Clients/a/HayStack_API.py", line 6, in <module>
    from DynamicPublicLedger_Module import Dynamic_Public_Ledger
  File "/home/XXX/github/Haystack/Test_Clients/a/DynamicPublicLedger_Module.py", line 6, in <module>
    from User_Modules import User_Profile
  File "/home/XXX/github/Haystack/Test_Clients/a/User_Modules.py", line 10, in <module>
    class Initialization(Configuration, Tools):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Configuration, Tools

This error is from the fact that in python2 the representation of string is different than to python3.

**Comment by ouya99** [comment]
btw python2 is only supported until end of 2019

**Comment by woywoy123** [comment]
Will try to first implement most of the features and then rewrite the code in python 3
