### ISSUE TITLE
Exception in thread Thread-3

### ISSUE THREAD

**Issue by ouya99** [ConsensusGroup/Haystack#20]
Happened without any action in following menu

log output:

Please choose one of the options: 
 a) Compose Message 
 b) Check Inbox 
 c) Add or remove Contacts 
 d) Go back 
>>> Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/afr0909/Dev/Haystack/HayStack_Client/HayStack_API.py", line 199, in run
    HayStack().Ping_Function()
  File "/home/afr0909/Dev/Haystack/HayStack_Client/HayStack_API.py", line 99, in Ping_Function
    Sender_Client().Ping_Function()
  File "/home/afr0909/Dev/Haystack/HayStack_Client/Haystack_Module.py", line 79, in Ping_Function
    Data = self.Send_Message(Message = Random, ReceiverAddress = Client_Public_Address, PublicKey = Client_Public_K
ey, Ping_Function = True)
  File "/home/afr0909/Dev/Haystack/HayStack_Client/Haystack_Module.py", line 36, in Send_Message
    hashed = self.PrivateIOTA.Send(ReceiverAddress = ToSend[1], Message = ToSend[0])
  File "/home/afr0909/Dev/Haystack/HayStack_Client/IOTA_Module.py", line 100, in Send
    send = self.IOTA_Api.send_trytes(trytes = coded, depth = 4)
  File "/usr/local/lib/python2.7/dist-packages/iota/api.py", line 1238, in send_trytes
    minWeightMagnitude=min_weight_magnitude,
  File "/usr/local/lib/python2.7/dist-packages/iota/commands/__init__.py", line 130, in __call__
    self.response = self._execute(self.request)
  File "/usr/local/lib/python2.7/dist-packages/iota/commands/extended/send_trytes.py", line 54, in _execute
    trytes=trytes,
  File "/usr/local/lib/python2.7/dist-packages/iota/commands/__init__.py", line 130, in __call__
    self.response = self._execute(self.request)
  File "/usr/local/lib/python2.7/dist-packages/iota/commands/core/attach_to_tangle.py", line 41, in _execute
    return super(FilterCommand, self)._execute(request)
  File "/usr/local/lib/python2.7/dist-packages/iota/commands/__init__.py", line 158, in _execute
    return self.adapter.send_request(request)
  File "/usr/local/lib/python2.7/dist-packages/iota/adapter/__init__.py", line 320, in send_request
    return self._interpret_response(response, payload, {codes['ok']})
  File "/usr/local/lib/python2.7/dist-packages/iota/adapter/__init__.py", line 465, in _interpret_response
    'response': decoded,
BadApiResponse: 429 response from node: {u'status': 429, u'timestamp': u'2019-11-23T16:17:54.279+0000', u'message':
 u'Rate limit reached or all nodes are busy. Try again later.', u'error': u'Too Many Requests', u'path': u'/'}

trying to quit is not easy ;)

`^CTraceback (most recent call last):
  File "main.py", line 329, in <module>
    Interactive_Client().Third_Screen()
  File "main.py", line 157, in Third_Screen
    User_Choice = raw_input("Please choose one of the options: \n a) Compose Message \n b) Check Inbox \n c) Add or
 remove Contacts \n d) Go back \n>>> ")
KeyboardInterrupt
^C^C^[d^[d^C^C
^C
^C`

**Comment by woywoy123** [comment]
I think I found a patch for this issue. Will patch this in the next commit.
